document.writeln("<div class=\"public\">");
document.writeln("    <link rel=\"stylesheet\" href=\"css/base.css\">");
document.writeln("    <link rel=\"stylesheet\" href=\"css/index.css\">");
document.writeln("    <!-- 公共部分 -->");
document.writeln("    <div class=\"background\">");
document.writeln("        <img src=\"image/base/index_background.jpg\" alt=\"#\">");
document.writeln("    </div>");
document.writeln("    <div class=\"to_top\">");
document.writeln("        <a href=\"#top\"><img src=\"image/base/top.png\" alt=\"去顶部\"></a>");
document.writeln("    </div>");
document.writeln("    <div class=\"shortcut clearfix\">");
document.writeln("        <img src=\"image/base/title.jpg\" alt=\"#\">");
document.writeln("        <div class=\"fl\">");
document.writeln("            <a href=\"http://www.fengtai.red\" style=\"background-image: url(image/base/a.png);\"></a>");
document.writeln("        </div>");
document.writeln("        <div class=\"fr\">");
document.writeln("            <ul>");
document.writeln("                <li id=\"gallery\"><a href=\"gallery.html\">图库</a></li>");
document.writeln("                <li id=\"tool\"><a href=\"tool.html\">工具</a></li>");
document.writeln("                <li id=\"website\"><a href=\"website.html\">网站</a></li>");
document.writeln("                <li id=\"blog\"><a href=\"blog.html\">博客</a></li>");
document.writeln("            </ul>");
document.writeln("        </div>");
document.writeln("    </div>");
document.writeln("</div>");
